name: FastFounder Daily Digest (Authenticated)

on:
  schedule:
    # Run daily at 9:15 AM MDT → 15:15 UTC
    - cron: '15 15 * * *'
  workflow_dispatch:

jobs:
  send-daily-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify FastFounder credentials
        run: |
          if [[ -z "$FAST_FOUNDER_EMAIL" || -z "$FAST_FOUNDER_PASSWORD" ]]; then
            echo "⚠️ FAST_FOUNDER_EMAIL/PASSWORD not set, falling back to public scraping"
          else
            echo "✅ FAST_FOUNDER_EMAIL/PASSWORD found"
          fi
        env:
          FAST_FOUNDER_EMAIL:    ${{ secrets.FAST_FOUNDER_EMAIL }}
          FAST_FOUNDER_PASSWORD: ${{ secrets.FAST_FOUNDER_PASSWORD }}

      - name: Run FastFounder Daily Bot (Authenticated)
        env:
          OPENAI_API_KEY:   ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_TOKEN:   ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FAST_FOUNDER_EMAIL:    ${{ secrets.FAST_FOUNDER_EMAIL }}
          FAST_FOUNDER_PASSWORD: ${{ secrets.FAST_FOUNDER_PASSWORD }}
        run: |
          echo "🚀 Starting FastFounder Daily Bot"
          echo "📅 Current time: $(date)"
          python3 main_authenticated.py

      - name: Upload logs (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: fastfounder-logs
          path: logs/
