name: FastFounder Daily Digest (Multi-User)

on:
  schedule:
    # Run daily at 9:15 AM MDT → 15:15 UTC
    - cron: '15 15 * * *'
  workflow_dispatch:

jobs:
  send-daily-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run FastFounder Daily Bot (Multi-User)
        env:
          OPENAI_API_KEY:        ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_TOKEN:        ${{ secrets.TELEGRAM_TOKEN }}
          FAST_FOUNDER_EMAIL:    ${{ secrets.FAST_FOUNDER_EMAIL }}
          FAST_FOUNDER_PASSWORD: ${{ secrets.FAST_FOUNDER_PASSWORD }}
        run: |
          echo "🚀 Starting FastFounder Daily Bot (Multi-User Version)"
          echo "📅 Current time: $(date)"
          echo "🔐 Checking authentication credentials..."
          
          if [ -z "$FAST_FOUNDER_EMAIL" ] || [ -z "$FAST_FOUNDER_PASSWORD" ]; then
            echo "⚠️ FastFounder credentials not found - will use fallback scraping"
          else
            echo "✅ FastFounder credentials found - will attempt authentication"
          fi
          
          echo "👥 Will broadcast to all users in users.json"
          python3 main_multiuser_daily.py
